name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # חשוב להוסיף את זה
          ref: main  # הוספת שורה זו

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Get old version
        id: get_old_version
        run: |
          old_version=$(yarn list --pattern israeli-bank-scrapers-core --depth=0 --json --non-interactive --no-progress | jq -r '.data.trees[].name' | cut -d'@' -f2)
          echo "old_version=${old_version}" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: yarn install

      - name: Upgrade israeli-bank-scrapers-core
        run: |
          yarn upgrade israeli-bank-scrapers-core --latest
      - name: Get new version
        id: get_new_version
        run: |
          new_version=$(yarn list --pattern israeli-bank-scrapers-core --depth=0 --json --non-interactive --no-progress | jq -r '.data.trees[].name' | cut -d'@' -f2)
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT
      - name: Generate diff link
        id: diff_link
        run: |
          echo "diff_link=https://github.com/eshaham/israeli-bank-scrapers/compare/v${{ steps.get_old_version.outputs.old_version }}...v${{ steps.get_new_version.outputs.new_version }}" >> $GITHUB_OUTPUT
      - name: Check default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          echo "DEFAULT_BRANCH=${DEFAULT_BRANCH}" >> $GITHUB_ENV
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'deps/israeli-bank-scrapers-core'
          base: ${{ env.DEFAULT_BRANCH }}
          delete-branch: true
          commit-message: |
            chore(deps): update israeli-bank-scrapers-core to ${{ steps.get_new_version.outputs.new_version }}
          title: |
            Update israeli-bank-scrapers-core to ${{ steps.get_new_version.outputs.new_version }}
          body: |
            עדכון אוטומטי של התלויות
            
            * מגרסה: ${{ steps.get_old_version.outputs.old_version }}
            * לגרסה: ${{ steps.get_new_version.outputs.new_version }}
            
            קישור להשוואת גרסאות: ${{ steps.diff_link.outputs.diff_link }}
          labels: dependencies
